node("master")
{
       stage("Continuous Download")
    {
        git 'http://github.com/sreekanthdev/mar20.git'
    }
    stage("ContinuousBuild")
    {
        sh 'mvn package'
    }
    stage("ContinuousDeployment")
    {
        sh 'scp /home/ubuntu/.jenkins/workspace/simplescript/webapp/target/webapp.war ubuntu@172.31.47.37:/var/lib/tomcat8/webapps/qaenv5.war'
    }
}
